version: '1.0'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: database 
    ports:
      - "3306:3306"

  filler:
    build:
      dockerfile: filler/Dockerfile
    environment:
      DB_HOST: db
    depends_on:
      - db


  



