version: '1.0'

services:
  db:
    image: mariadb
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE} 
    ports:
      - "3306:3306"
    networks:
      - my-bridge-network

  filler:
    build:
      dockerfile: filler/Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: db
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      TABLE_NAME: ${TABLE_NAME}
    volumes:
      - ./data.csv:/srv/data.csv
      - ./filler/fill.py:/srv/fill.py
    depends_on:
      - db
    networks:
      - my-bridge-network

  # web:
  #   build:
  #     dockerfile: web/Dockerfile
  #   env_file:
  #     - .env
  #   environment:
  #     DB_HOST: db
  #   depends_on:
  #     - filler
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - my-bridge-network

networks:
  my-bridge-network:
    driver: bridge
    


  



