version: "2.2"

services:
  ubuntu:
    image: ubuntu_custom
    restart: always
    stdin_open: true
    tty: true
    container_name: ubuntu_hw3
    ports:
      - "80:80"
    


    




    


  



